### ISSUE TITLE
Missing experiment number in output surface plot

### ISSUE THREAD

**Issue by AndresSepulveda** [trondkr/Chile-IBM#5]
To add the experiment loop to the output plot file, L115

plotfile_name = 'Figures/' + pre[0:-1] + '_plot.png'

should be changed to

plotfile_name = 'Figures/' + pre[0:-1] +srt(confobj.experiment)+ '_plot.png'

**Comment by trondkr** [comment]
Fixed in commit c46e9fc86563f77b3184231572e28ceea3747795
